from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage

from iot_agentic_deployer.clients.thingsboard_client import ThingsBoardClient
from iot_agentic_deployer.state import IoTDeploymentState
from iot_agentic_deployer.nodes.intent import OrchestratorNode
from iot_agentic_deployer.nodes.deployment_agent_node import DeploymentAgentNode
from iot_agentic_deployer.nodes.iot_retreival_node import IoTRetrievalNode
import os
from dotenv import load_dotenv

import sqlite3
from langgraph.checkpoint.sqlite import SqliteSaver

class IoTAgenticWorkflow:
    """Manages the configuration and compilation of the LangGraph workflow."""

    def __init__(self, db_path: str = "iot_agentic.db"):
        load_dotenv()
        self.llm = ChatOpenAI(
            base_url="https://openrouter.ai/api/v1",
            model=os.getenv("OPENAI_MODEL"),
            api_key=os.getenv("OPENAI_API_KEY"),
        )

        # One ThingsBoard client, shared by every node that needs it.
        self.tb_client = ThingsBoardClient()

        # Persists every chat's full state (messages, next_node, dt_data, ...)
        # per thread_id. This is what lets the UI offer "new chat" / "previous
        # chats" without manually shuttling a state dict around anymore -
        # LangGraph restores/saves it automatically on every .stream() call.
        conn = sqlite3.connect(db_path, check_same_thread=False)
        self.checkpointer = SqliteSaver(conn)


        # Single source of truth for what's in the graph.
        # To add a node: add one line here. Nothing else needs to change -
        # the Orchestrator's valid routing targets are derived from these
        # keys too, so the prompt can never drift out of sync with the graph.
        operational_nodes = {
            "IoTRetrievalNode": IoTRetrievalNode(self.tb_client),
            "DeploymentAgent": DeploymentAgentNode(self.tb_client),
        }

        self.nodes = {
            "Orchestrator": OrchestratorNode(llm=self.llm, valid_destinations=list(operational_nodes.keys())),
            **operational_nodes,
        }

        self.workflow = StateGraph(IoTDeploymentState)
        self._setup_nodes()
        self._setup_edges()
        self.system = self.workflow.compile(checkpointer=self.checkpointer)

    def _setup_nodes(self):
        for name, node in self.nodes.items():
            self.workflow.add_node(name, node)

    def _deterministic_router(self, state: IoTDeploymentState) -> str:
        """Reads the state and routes the flow generated by the Orchestrator."""
        destination = state.get("next_node", "WaitUser")
        return END if destination == "WaitUser" else destination

    def _setup_edges(self):
        self.workflow.set_entry_point("Orchestrator")

        # Every node except the Orchestrator is an "operational" node:
        # the Orchestrator can route to it, and it always returns control
        # to the Orchestrator afterwards.
        operational_nodes = [name for name in self.nodes if name != "Orchestrator"]

        routing_map = {name: name for name in operational_nodes}
        routing_map[END] = END

        self.workflow.add_conditional_edges("Orchestrator", self._deterministic_router, routing_map)

        for name in operational_nodes:
            self.workflow.add_edge(name, "Orchestrator")

    def run_turn(self, thread_id: str, user_input: str) -> str:
        """Runs one turn of a given chat and returns the assistant's reply.

        Only the new message is passed in - the checkpointer restores the
        rest of that thread's state automatically and saves the updated
        state back under the same thread_id.
        """
        config = {"configurable": {"thread_id": thread_id}}
        final_state = None
        for event in self.system.stream({"messages": [HumanMessage(content=user_input)]}, config=config,
                                        stream_mode="values"):
            final_state = event
        return final_state["messages"][-1].content

    def get_history(self, thread_id: str) -> list:
        """Returns the message history for a given chat (empty if it's new)."""
        config = {"configurable": {"thread_id": thread_id}}
        snapshot = self.system.get_state(config)
        if snapshot and snapshot.values:
            return snapshot.values.get("messages", [])
        return []
    
    def get_dt_data(self, thread_id: str) -> list:
        """Returns the latest retrieved device data for a given chat (empty if none yet)."""
        config = {"configurable": {"thread_id": thread_id}}
        snapshot = self.system.get_state(config)
        if snapshot and snapshot.values:
            return snapshot.values.get("dt_data", [])
        return []

    def run(self):
        """Starts an interactive CLI session (single, ad-hoc chat)."""
        print("\n--- Starting Agentic IoT Session (Type 'exit' to quit) ---")
        thread_id = "cli-session"

        while True:
            user_input = input("\nOperator: ")
            if user_input.lower() in ['exit', 'quit']:
                break

            reply = self.run_turn(thread_id, user_input)
            print(f"\nSystem: {reply}")

